# render.yaml
services:
  - type: web
    name: silent-scan-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: VIRUSTOTAL_API_KEY
        value: b91d93e405427b32ef60f09bf99543227381e52989dda801517cf16d2960b9b7